import { Actor, HttpAgent } from '@dfinity/agent';
// Import from generated declarations - these are auto-generated by dfx
// @ts-ignore - declarations are generated at build time
import { idlFactory } from '../declarations/backend';
import { type backendInterface } from '../backend';

// Load environment configuration
export interface EnvConfig {
  BACKEND_CANISTER_ID: string;
  DFX_NETWORK: string;
  HOST?: string;
}

let envConfig: EnvConfig | null = null;

/**
 * Load configuration from env.json (production) or environment variables (development)
 */
export async function loadConfig(): Promise<EnvConfig> {
  if (envConfig) return envConfig;

  try {
    // Try to load from env.json (production build)
    const response = await fetch('/env.json');
    if (response.ok) {
      const config = await response.json();
      
      // Validate required fields
      if (!config.BACKEND_CANISTER_ID || config.BACKEND_CANISTER_ID.trim() === '') {
        throw new Error('env.json is missing or has empty BACKEND_CANISTER_ID');
      }
      
      if (!config.DFX_NETWORK || config.DFX_NETWORK.trim() === '') {
        throw new Error('env.json is missing or has empty DFX_NETWORK');
      }
      
      envConfig = config;
      console.log('✅ Loaded config from env.json:', {
        canisterId: config.BACKEND_CANISTER_ID,
        network: config.DFX_NETWORK,
      });
      return config;
    } else {
      console.warn(`env.json returned status ${response.status}, falling back to environment variables`);
    }
  } catch (error) {
    console.warn('Could not load env.json:', error);
    console.warn('Falling back to environment variables');
  }

  // Fallback to environment variables (development)
  const config: EnvConfig = {
    BACKEND_CANISTER_ID:
      import.meta.env.VITE_BACKEND_CANISTER_ID ||
      import.meta.env.CANISTER_ID_BACKEND ||
      '',
    DFX_NETWORK: import.meta.env.DFX_NETWORK || 'local',
    HOST: import.meta.env.VITE_HOST,
  };

  if (!config.BACKEND_CANISTER_ID || config.BACKEND_CANISTER_ID.trim() === '') {
    throw new Error(
      'Backend canister ID not found. Please ensure BACKEND_CANISTER_ID is set in /env.json (production) or environment variables (development).'
    );
  }

  envConfig = config;
  console.log('✅ Loaded config from environment variables:', {
    canisterId: config.BACKEND_CANISTER_ID,
    network: config.DFX_NETWORK,
  });
  return config;
}

/**
 * Create an actor with proper configuration for both authenticated and anonymous calls.
 * Handles local development (with root key fetching) and production deployment.
 */
export async function createActorWithConfig(
  options?: {
    agentOptions?: {
      identity?: any;
      host?: string;
    };
  }
): Promise<backendInterface> {
  const config = await loadConfig();

  if (!config.BACKEND_CANISTER_ID) {
    throw new Error(
      'Backend canister ID not found. Please ensure BACKEND_CANISTER_ID is set in /env.json or environment variables.'
    );
  }

  // Determine host based on network
  const isLocal = config.DFX_NETWORK !== 'ic';
  const host =
    options?.agentOptions?.host ||
    config.HOST ||
    (isLocal ? 'http://127.0.0.1:4943' : 'https://icp-api.io');

  console.log('🔧 Creating actor with config:', {
    canisterId: config.BACKEND_CANISTER_ID,
    host,
    network: config.DFX_NETWORK,
    hasIdentity: !!options?.agentOptions?.identity,
  });

  // Create HTTP agent
  const agent = new HttpAgent({
    host,
    ...options?.agentOptions,
  });

  // Fetch root key for local development only
  // This is required for anonymous calls to work in local replica
  if (isLocal) {
    try {
      await agent.fetchRootKey();
      console.log('✅ Fetched root key for local development');
    } catch (error) {
      console.error('❌ Failed to fetch root key:', error);
      throw new Error(
        'Failed to fetch root key. Make sure the local replica is running with `dfx start`'
      );
    }
  }

  // Create and return actor
  const actor = Actor.createActor<backendInterface>(idlFactory, {
    agent,
    canisterId: config.BACKEND_CANISTER_ID,
  });

  console.log('✅ Actor created successfully');
  return actor;
}
