/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubmissionId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Submission = IDL.Record({
  'id' : SubmissionId,
  'paymentStatus' : PaymentStatus,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'plan' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'paymentDate' : IDL.Opt(IDL.Int),
  'paymentTime' : IDL.Opt(IDL.Int),
  'renewalDate' : IDL.Opt(IDL.Int),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SubmissionId],
      [],
    ),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRemainingUrgencySlots' : IDL.Func([], [IDL.Nat], ['query']),
  'getStaticConfigInstructions' : IDL.Func([], [IDL.Text], []),
  'getSubmissionById' : IDL.Func(
      [SubmissionId],
      [IDL.Opt(Submission)],
      ['query'],
    ),
  'helloWorld' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsPaid' : IDL.Func([SubmissionId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubmissionId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Submission = IDL.Record({
    'id' : SubmissionId,
    'paymentStatus' : PaymentStatus,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'plan' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'paymentDate' : IDL.Opt(IDL.Int),
    'paymentTime' : IDL.Opt(IDL.Int),
    'renewalDate' : IDL.Opt(IDL.Int),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SubmissionId],
        [],
      ),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRemainingUrgencySlots' : IDL.Func([], [IDL.Nat], ['query']),
    'getStaticConfigInstructions' : IDL.Func([], [IDL.Text], []),
    'getSubmissionById' : IDL.Func(
        [SubmissionId],
        [IDL.Opt(Submission)],
        ['query'],
      ),
    'helloWorld' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsPaid' : IDL.Func([SubmissionId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };