/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export interface Submission {
  'id' : SubmissionId,
  'paymentStatus' : PaymentStatus,
  'owner' : Principal,
  'name' : string,
  'plan' : string,
  'whatsapp' : string,
  'email' : string,
  'timestamp' : bigint,
  'paymentDate' : [] | [bigint],
  'paymentTime' : [] | [bigint],
  'renewalDate' : [] | [bigint],
}
export type SubmissionId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSubmission' : ActorMethod<[string, string, string], SubmissionId>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRemainingUrgencySlots' : ActorMethod<[], bigint>,
  'getStaticConfigInstructions' : ActorMethod<[], string>,
  'getSubmissionById' : ActorMethod<[SubmissionId], [] | [Submission]>,
  'helloWorld' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsPaid' : ActorMethod<[SubmissionId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];